# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python.

Numpy is also incredibly fast, as it has bindings to C libraries.

## Installation Instructions

**If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    !pip install numpy
    

In [1]:
!pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

# Numpy Arrays

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
array1=np.array(my_list)
type(array1)

 


numpy.ndarray

In [6]:
print(array1)

[1 2 3]


In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

print(my_matrix)
print(type(my_matrix))


[[1, 2, 3], [4, 5, 6], [7, 9]]
<class 'list'>


In [12]:
print(np.array(my_matrix))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
np1 = np.array(my_matrix)
type(np1)

numpy.ndarray

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#np.zeros( 3,3 ) #Error

print(np.zeros( (3,3) ))
np.zeros( (3,3,2) )


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
dim1 = (2,5,5)

print(type(dim1))

np.zeros(dim1)

<class 'tuple'>


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [31]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.ones( (3,3)  )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [34]:
np.linspace(0,200,51)

array([  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,
        44.,  48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,  80.,  84.,
        88.,  92.,  96., 100., 104., 108., 112., 116., 120., 124., 128.,
       132., 136., 140., 144., 148., 152., 156., 160., 164., 168., 172.,
       176., 180., 184., 188., 192., 196., 200.])

In [35]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [36]:
np.eye( 6 )

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [38]:
np.random.rand(5)

array([0.6899041 , 0.37556745, 0.64825784, 0.84363105, 0.0556639 ])

In [39]:
np.random.rand(5,5)

array([[0.87747645, 0.86750102, 0.53438079, 0.50103959, 0.41964309],
       [0.24479786, 0.23196309, 0.12819562, 0.12188711, 0.41591447],
       [0.0860155 , 0.06367008, 0.62915507, 0.75442035, 0.69711152],
       [0.13190724, 0.56641133, 0.66428057, 0.22997046, 0.06404991],
       [0.35166136, 0.1476884 , 0.7466503 , 0.07483764, 0.33978441]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [41]:
np.random.randint(1,1000)

964

In [43]:
np.random.randint(1,100,10)

array([35, 53, 66, 63, 98, 80, 75, 16, 17, 39])

In [44]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
ranarr

array([38,  4,  3,  4,  1, 46, 30, 47, 16,  9])

## Reshape
Returns an array containing the same data with a new shape.

In [52]:
print(arr)

arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [53]:
ranarr

array([38,  4,  3,  4,  1, 46, 30, 47, 16,  9])

In [54]:
ranarr.max()

47

In [55]:
ranarr.argmax()

7

In [56]:
ranarr.min()

1

In [57]:
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [59]:
print(arr.dtype)
arr2 = arr/2
print(arr2.dtype)
arr2
arr2.dtype
print(arr2)

int64
float64
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12. ]
