# NumPy Operations

In [ ]:
from numpy import arange
from timeit import Timer

Nelements = 10000
Ntimeits = 10000

x = arange(Nelements)
y = range(Nelements)

t_numpy = Timer("x.sum()", "from __main__ import x")
t_list = Timer("sum(y)", "from __main__ import y")
print("numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits,))
print("list:  %.3e" % (t_list.timeit(Ntimeits)/Ntimeits,))

numpy: 7.291e-05
list:  1.791e-03


## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
import numpy as np
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(10, 50,20).reshape(4,5)
b = np.random.randint(10, 50,25).reshape(5,5)
a1 = np.random.randint(10, 50,20).reshape(4,5)


In [ ]:
print(a)

[[48 40 45 10 46]
 [11 42 37 24 44]
 [42 26 47 41 20]
 [22 28 41 31 39]]


In [ ]:
print(b)

[[38 13 23 38 37]
 [25 18 14 10 23]
 [35 17 39 18 40]
 [17 35 42 44 47]
 [20 18 36 36 19]]


In [ ]:
print(a1)
a * a1

[[24 26 47 45 33]
 [23 32 41 32 47]
 [24 32 25 37 45]
 [32 19 11 23 20]]


array([[1152, 1040, 2115,  450, 1518],
       [ 253, 1344, 1517,  768, 2068],
       [1008,  832, 1175, 1517,  900],
       [ 704,  532,  451,  713,  780]])

In [ ]:
a.dot(b)

array([[5489, 3287, 5495, 5130, 5840],
       [4051, 3160, 4876, 4144, 4817],
       [4988, 3608, 5605, 5226, 6339],
       [4278, 3274, 5203, 4622, 5296]])

In [ ]:
# 5 = 00101
# 9 = 01001
#   = 01101
np.bitwise_or(5, 9)


13

In [ ]:
print(arr)
arr[np.logical_and(arr>2, arr<5)]

[0 1 2 3 4 5 6 7 8 9]


array([3, 4])

In [ ]:
np.isnan(np.log(0))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


False